# Captures the git identity of the working tree into a generated header.
#
# Run as a script (cmake -P) from a build-time custom target, not at configure time: a sha
# captured at configure time goes stale the moment anyone commits, and a manifest field that
# names the wrong commit is worse than one that says "unknown".
#
# The file is only rewritten when its contents CHANGE, so this does not force a rebuild of
# every dependent on every build.
#
# Inputs: PERCEPTION_SOURCE_DIR, PERCEPTION_OUTPUT_FILE

set(git_sha "unknown")
set(git_describe "unknown")
set(git_dirty "false")

find_package(Git QUIET)
if(GIT_FOUND)
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" rev-parse HEAD
    WORKING_DIRECTORY "${PERCEPTION_SOURCE_DIR}"
    OUTPUT_VARIABLE sha_output
    ERROR_QUIET
    RESULT_VARIABLE sha_result
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  if(sha_result EQUAL 0 AND sha_output)
    set(git_sha "${sha_output}")
  endif()

  execute_process(
    COMMAND "${GIT_EXECUTABLE}" describe --always --dirty --tags
    WORKING_DIRECTORY "${PERCEPTION_SOURCE_DIR}"
    OUTPUT_VARIABLE describe_output
    ERROR_QUIET
    RESULT_VARIABLE describe_result
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  if(describe_result EQUAL 0 AND describe_output)
    set(git_describe "${describe_output}")
  endif()

  # `status --porcelain` covers tracked modifications and staged changes. Untracked files are
  # deliberately NOT counted as dirty here: the whole perception/ tree is untracked in this
  # repository right now, so counting them would pin `dirty` to true forever and the flag
  # would stop carrying information.
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" status --porcelain --untracked-files=no
    WORKING_DIRECTORY "${PERCEPTION_SOURCE_DIR}"
    OUTPUT_VARIABLE status_output
    ERROR_QUIET
    RESULT_VARIABLE status_result
  )
  if(status_result EQUAL 0 AND NOT status_output STREQUAL "")
    set(git_dirty "true")
  endif()
endif()

set(generated_contents
"// GENERATED by perception/cmake/GenerateBuildInfo.cmake at build time. Do not edit and do
// not commit: it is a build artefact, regenerated whenever the git state changes.
#ifndef PERCEPTION_GENERATED_BUILD_INFO_H_
#define PERCEPTION_GENERATED_BUILD_INFO_H_

#define PERCEPTION_GIT_SHA \"${git_sha}\"
#define PERCEPTION_GIT_DESCRIBE \"${git_describe}\"
#define PERCEPTION_GIT_DIRTY ${git_dirty}

#endif  // PERCEPTION_GENERATED_BUILD_INFO_H_
")

set(existing_contents "")
if(EXISTS "${PERCEPTION_OUTPUT_FILE}")
  file(READ "${PERCEPTION_OUTPUT_FILE}" existing_contents)
endif()

if(NOT existing_contents STREQUAL generated_contents)
  get_filename_component(output_directory "${PERCEPTION_OUTPUT_FILE}" DIRECTORY)
  file(MAKE_DIRECTORY "${output_directory}")
  file(WRITE "${PERCEPTION_OUTPUT_FILE}" "${generated_contents}")
  message(STATUS "perception: build info updated (git ${git_sha}, dirty=${git_dirty})")
endif()
